title: Sunny Balasubramanian
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> Current quantitative researcher in the equities space. Formerly at Citadel, AQR, Columbia SEAS '16. Always cracking away at new (sometimes whimsical) problems using different kinds of technology. Please reach out to me at sunny.m.bala@gmail.com if you'd like to chat about any of my prior work or would like to hack on something together.
  <br><br>
  <a href="https://www.linkedin.com/in/sunnybala/"> LinkedIn </a><br><br>
  <a href="https://github.com/sunnybala"> GitHub </a> 
  
theme: jekyll-theme-minimal
google_analytics: G-DVYXGVQYJ6 # your Google Analytics tracking ID here
